### ISSUE TITLE
[Bug]: Something is up with authorization on the OpenAPI data sources

### ISSUE THREAD

**Issue by LennardF1989** [lowcoder-org/lowcoder#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've tried two OpenAPI specs:
- https://api.timechimp.com/swagger/docs/v1 (which uses `apiKey` with an `Authorization` header)
- https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/core/6.1/core.json (which uses `basic`)

No matter the values I tried, I could never get the API's to properly authenticate. Whereas if I use the plain REST API and setup the authorization headers accordingly, the endpoint work fine.

### Expected Behavior

The API's actually authenticate properly depending on their type.

### Steps to reproduce

Use the above OpenAPI specs, or find something else you as a developer have access to, and try to get the different types of authorization to work.

### Additional Information

I've tried to go through the code and see if I could spot something glaringly wrong. I couldn't, but I have a feeling the authorization headers aren't properly set on the fetch-request. ~~That said, I will see if I can inspect it using the Inspector...~~ Nope.

**Comment by FalkWolsky** [comment]
As we worked heavy on OAuth (Generic Provider), these issues should be solved now.
If they remain problematic for you - please just re-open the issue.

**Comment by Insomniacnomis** [comment]
I have this issue in my instance, being unable to access the API with an API key.
Giving the API key as an "Authorization" header, the call is returned as if no user is logged in.

As an example, running the following `curl` command:
```bash
curl \
	--location 'http://<DOMAIN>//api/users/me' \
	--header 'Accept: */*' \
	--header 'Authorization: ey...<REST OF THE API KEY>'
```
Returns as if the user is anonymous:
 ```JSON
{"code":1,"message":"","data":{
	"id":null,
	"orgAndRoles":null,
	"currentOrgId":null,
	"username":"anonymous",
	"connections":null,
	"uiLanguage":"en",
	"avatar":null,
	"avatarUrl":null,
	"hasPassword":false,
	"hasSetNickname":false,
	"hasShownNewUserGuidance":false,
	"userStatus":null,
	"createdTimeMs":0,
	"ip":"X.X.X.X",
	"enabled":false,
	"anonymous":true,
	"orgDev":false,
	"isAnonymous":true,
	"isEnabled":false},
"success":true}
```

**Comment by FalkWolsky** [comment]
The reason is a "missing" Bearer word before the actual Token.
It should be --header 'Authorization: Bearer ey...<REST OF THE API KEY>'

<img width="844" alt="Screenshot 2024-09-05 at 22 15 37" src="https://github.com/user-attachments/assets/e99a7010-dca2-45f7-a598-9bd11900eb70">

**Comment by Insomniacnomis** [comment]
> The reason is a "missing" Bearer word before the actual Token. It should be --header 'Authorization: Bearer ey...'
> <img alt="Screenshot 2024-09-05 at 22 15 37" width="844" src="https://private-user-images.githubusercontent.com/3671017/364935826-e99a7010-dca2-45f7-a598-9bd11900eb70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Njk0NjEsIm5iZiI6MTcyNTU2OTE2MSwicGF0aCI6Ii8zNjcxMDE3LzM2NDkzNTgyNi1lOTlhNzAxMC1kY2EyLTQ1ZjctYTU5OC05YmQxMTkwMGViNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMjA0NjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNmNTgwNmE3MTg1Zjc2Nzg5YTk3ODhmNjdiODI0NDAyYzdhYTg5ZDI1YmZiNmZmODdjNzEzMzE0ZTRmMjIyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cS5jp2YCeLAnQ3T18VR2XIWZawSnmGsdS1DB608NOSA">

I have tried it with and without Bearer, and the result is still the same. And a bunch of other combinations with the same result
Also, I am now checking that the cookie method isn't working either; neither with the cookie obtained with the API login (funny, that one does seem to work) nor a cookie copied from my web browser logged session.

I am running on Docker the version 2.4 if that matters
